services:

  node-app:
    image: rohan0125/node-devops-app
    container_name: node-app
    networks:
      - devops-net

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/rohang/devops-project/nginx:/etc/nginx/conf.d/ 
    depends_on:
      - node-app
    networks:
      - devops-net

networks:
  devops-net:
